### PR TITLE
Fix logstream listing and deletion

### LINKED ISSUE #54: Verify valid streams on startup and make sure stream is properly deleted
When a stream is deleted it is removed from the object store and metadata. In case of it being an active stream there might be parquet files for it in local directory waiting to be synced or might already be synced just after deletion. This behaviour causes it to be loaded as a stream again because a root level prefix is created on storage by s3 sync. 

Possible fixes
- Check for .schema on each stream when loading for metadata
- Clean up code that cleans invalid streams if any

### PR DESCRIPTION
**Pull request by trueleo**
Fixes #54 .

- #### Delete local data when stream is deleted.

- #### Use `/.schema` as prefix when listing streams.
    As s3 sync is an independent thread there is no guarantee of ordering between when stream list is read and when it is deleted. However when a stream is deleted then it's .schema is gone. So by checking for .schema valid streams can be listed.

<hr>

This PR has:
- [ ] been tested to ensure log ingestion and log query works.
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added documentation for new or modified features or behaviors.

### CODE REVIEW

File: server/src/handlers/logstream.rs [hunk 1]
```diff
@@ -46,21 +48,30 @@ pub async fn delete(req: HttpRequest) -> HttpResponse {
         .to_http();
     }
 
-    if let Err(e) = s3.delete_stream(&stream_name).await {
+    if let Err(e) = metadata::STREAM_INFO.delete_stream(&stream_name) {
```
Comment (nitisht) [inline server/src/handlers/logstream.rs:51]: order of deletion matters here. First delete from s3 because that has highest probability to fail. Only on successfully deleting from s3, attempt local directory and then metadata

If s3 deletion fails, fail the api
if s3 delete worked and local dir delete failed, respond with 200 in api response and log on console about failed delete in local data dir.
if s3 and local dir delete worked and metadata delete failed, same as second case, api is successful and error log on console about exact failure
