### PR TITLE
Fix auth issue

### LINKED ISSUE #17: [UI] do not store username and password in local store
We don't need to store the username and password in local store. Let's remove that code.

### PR DESCRIPTION
**Pull request by ameen4455**
Fixes #17

This PR has:
- [ ] been tested to ensure log ingestion and log query works.
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added documentation for new or modified features or behaviors.

### CODE REVIEW

File: ui/src/page/Login/index.js [hunk 1]
```diff
@@ -31,12 +31,9 @@ const Login = () => {
...
       localStorage.setItem("auth", credentials);
       localStorage.setItem("username", username);
-      localStorage.setItem("password", password);
       try {
-        const res = await getLogStream();
-        if (res.statusText === "OK") {
-          navigate("/index.html");
-        }
+        await getLogStream();
+        navigate("/index.html");
```
Comment (nitisht) [inline ui/src/page/Login/index.js:36]: But this would mean no check at all right? If the `getLogStream()` function failed wouldn't this still navigate to `index.html`

Comment (ameen4455) [reply ui/src/page/Login/index.js:36]: If the request fails, it would be caught by the try catch block

Comment (nitisht) [reply ui/src/page/Login/index.js:36]: so anything other than 200 https status would be a failure here?

Comment (ameen4455) [reply ui/src/page/Login/index.js:36]: 4XX would be considered failure

Comment (nitisht) [reply ui/src/page/Login/index.js:36]: okay, then we're good.

**Review by nitisht — APPROVED** [review]
