### PR TITLE
Manage sync threads failures

### LINKED ISSUE #43: Mechanism to ensure local data sync thread is always running
The local data sync thread is responsible for moving the data to a local directory and then move it to object storage as needed. If this thread crashes for any reason, we should be able detect that, try restarting the thread. 

If the thread can't be respawned due to whatever reasons, the server should at the end of granularity period should stop taking post events (because we can't ensure data integrity).

### PR DESCRIPTION
**Pull request by trueleo**
Fixes #43

### Description

This PR makes bunch of changes to ways how local sync and s3 sync threads are managed inside parseable. The goal is to make parseable main thread be aware of unwanted failure inside either of these dedicated sync thread. Additionally we want to have control over life cycle of these threads and have them stop on command, This can be later explored in future if we want to have graceful shutdown an also to guarantee more data consistency in case of failure.

#### This solution works something like this :-
Sync threads are spawned with pair of one shot channels (named with suffix inbox and outbox) for communication with main thread.

- inbox is sender type which can be used to stop the respective thread by breaking its scheduler loop.
- outbox is receiver type which is polled inside the main thread's looped select. So that whenever we receive a message from thread we stop.     

scheduler is ran inside loop which runs pending tasks and polls the channel for any message from main thread ( if any then stop the thread )

All of this is wrapped by a catch unwind. So in case of an unwinding because of panic there is a chance to let main thread know and handle accordingly. This is added as a safeguard for now but later we need to verify that local_sync and s3_sync don't have anything that can panic.

<hr>

This PR has:
- [ ] been tested to ensure log ingestion and log query works.
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added documentation for new or modified features or behaviors.

### CODE REVIEW

File: server/src/main.rs [hunk 1]
```diff
@@ -63,33 +67,110 @@ async fn main() -> anyhow::Result<()> {
...
+                s3sync_inbox.send(()).unwrap_or(());
+                localsync_inbox.send(()).unwrap_or(());
+                localsync_handler.join().unwrap_or(());
+                s3sync_handler.join().unwrap_or(());
+                return e
+            },
+            _ = &mut localsync_outbox => {
+                // crash the server if localsync fails for any reason
+                // panic!("Local Sync thread died. Server will fail now!")
+                return Err(anyhow::Error::msg("Local Sync failed"))
```
Comment (nitisht) [inline server/src/main.rs:89]: Let's improve the error message here. User might not know what is local sync. Let's say

```
Failed to sync local data to disc. This can happen due to critical error in disc or environment. Please restart the Parseable server. 

Join us on Parseable Slack if the issue persists after restart : https://launchpass.com/parseable
```

File: server/src/main.rs [hunk 2]
```diff
@@ -63,33 +67,110 @@ async fn main() -> anyhow::Result<()> {
...
+            scheduler
+                .every((storage::LOCAL_SYNC_INTERVAL as u32).seconds())
+                .run(move || {
+                    if let Err(e) = S3::new().local_sync() {
+                        warn!("failed to sync local data. {:?}", e);
+                    }
+                });
+
+            loop {
+                thread::sleep(Duration::from_millis(50));
```
Comment (trueleo) [inline server/src/main.rs:155]: Is it okay to thread sleep here for small amount of time ?

Comment (nitisht) [reply server/src/main.rs:155]: Why is sleep needed here?
